// Renders the generated blocks of a component README: the prop tables between
// `props:start` / `props:end` and the enum table between `enums:start` /
// `enums:end`.
//
// This lives apart from `readme-props.mjs` so that `check-readme.mjs` can ask
// the same question -- "what should this block say?" -- by calling the same
// code rather than by spawning the generator or, worse, by reimplementing the
// rules. A table generated under one set of rules and validated under another
// is the failure this whole effort exists to remove.

import path from "node:path";

import prettier from "prettier";

import { ROOT } from "./readme-program.mjs";

export const PROPS_BLOCK =
  /<!-- props:start(?: ([A-Za-z0-9_]+))? -->[\s\S]*?<!-- props:end -->/g;

export const ENUMS_BLOCK = /<!-- enums:start -->[\s\S]*?<!-- enums:end -->/g;

// Two props React declares that a consumer passes deliberately and that change
// what the component does. Every other inherited React prop collapses into the
// closing line: TextInput alone has about three hundred of them.
const PROMOTED_REACT_PROPS = new Set(["children", "ref"]);

const MAX_TYPE_LENGTH = 120;

const cell = (text) => text.replaceAll("|", "\\|");

const code = (text) => `\`${cell(text)}\``;

const typeCell = (type) =>
  code(
    type.length > MAX_TYPE_LENGTH
      ? `${type.slice(0, MAX_TYPE_LENGTH - 1)}…`
      : type,
  );

const describeCell = (prop) =>
  cell(
    prop.deprecated
      ? `**Deprecated.** ${prop.deprecatedReason || prop.description}`.trim()
      : prop.description,
  );

const table = (props) =>
  [
    "| Prop | Type | Required | Default | Description |",
    "| --- | --- | --- | --- | --- |",
    ...props.map((prop) =>
      [
        "",
        code(prop.name),
        typeCell(prop.type),
        prop.optional ? "no" : "**yes**",
        prop.default ? code(prop.default) : "–",
        describeCell(prop),
        "",
      ].join(" | "),
    ),
  ].join("\n");

/** Required props first, then alphabetical: the reader's first question. */
const ordered = (props) =>
  [...props].sort(
    (a, b) =>
      Number(a.optional) - Number(b.optional) || a.name.localeCompare(b.name),
  );

const englishList = (items) =>
  items.length <= 1
    ? (items[0] ?? "")
    : `${items.slice(0, -1).join(", ")} and ${items.at(-1)}`;

const groupBy = (items, key) => {
  const groups = new Map();

  for (const item of items) {
    const value = key(item);
    if (!groups.has(value)) groups.set(value, []);
    groups.get(value).push(item);
  }

  return groups;
};

const isPromoted = (prop) =>
  prop.origin !== "external" || PROMOTED_REACT_PROPS.has(prop.name);

// What belongs in the component's own table: what it declares, and what it
// picked out of a foreign type by name.
const isOwn = (prop) => prop.origin === "own" || prop.origin === "picked";

export const propsMarkdown = (resolved) => {
  const lines = [];
  const source = resolved.typeFile
    ? path.posix.basename(resolved.typeFile)
    : resolved.typeName;

  lines.push(
    `_Generated by \`pnpm readme:props\` from \`${resolved.typeName}\` in \`${source}\`. Do not edit; edit the JSDoc._`,
    "",
  );

  const all = resolved.baseProps;
  const own = all.filter((prop) => isOwn(prop) && !prop.portal);
  const portal = all.filter((prop) => isOwn(prop) && prop.portal);
  const inherited = all.filter((prop) => prop.origin === "kit" && !prop.portal);
  const external = all.filter((prop) => prop.origin === "external");

  lines.push(table(ordered([...own, ...external.filter(isPromoted)])), "");

  // Sorted by folder for the same reason the collapsed line below is sorted:
  // `groupBy` keeps first-encounter order, and the order the checker hands back
  // the properties of an intersection depends on what the program resolved
  // earlier. PasswordInput inherits from both input-block and text-input, and
  // its two groups swapped places between a `--only` run and a full one.
  const inheritedGroups = [...groupBy(inherited, (p) => p.ownerFolder)].sort(
    ([a], [b]) => a.localeCompare(b),
  );

  for (const [folder, props] of inheritedGroups) {
    const from = props[0].declaredIn ?? path.posix.basename(folder);
    lines.push(
      `#### Inherited from \`${from}\``,
      "",
      `Declared by [\`${folder}\`](../../${folder}/README.md) and accepted here too.`,
      "",
      table(ordered(props)),
      "",
    );
  }

  if (resolved.wrapperProps.length > 0) {
    lines.push(
      "#### Added by the wrapper the folder exports",
      "",
      "The `index` module exports a wrapped component, so these are accepted on top of the props above.",
      "",
      table(ordered(resolved.wrapperProps.filter(isPromoted))),
      "",
    );
  }

  if (portal.length > 0) {
    lines.push(
      "#### Portal-only props",
      "",
      "These need DocSpace portal context and do nothing in a standalone app.",
      "",
      table(ordered(portal)),
      "",
    );
  }

  const collapsed = external.filter((prop) => !isPromoted(prop));

  if (collapsed.length > 0) {
    // Sorted, so the line does not depend on the order the checker happens to
    // hand back properties in.
    const interfaces = [
      ...new Set(collapsed.map((prop) => prop.declaredIn).filter(Boolean)),
    ]
      .sort()
      .map((name) => `\`React.${name}\``);

    lines.push(
      `Plus ${collapsed.length} more props inherited from ${englishList(interfaces)}, forwarded to the element.`,
      "",
    );
  }

  return lines.join("\n").trimEnd();
};

/**
 * One table for the whole README, however many `props:start` markers it has.
 * Each marker is resolved on its own and each resolution dedupes only against
 * itself, so a README with several tables -- Table has seven, Selector six --
 * used to print `SelectorAccessRightsMode` once per marker.
 */
const enumsMarkdown = (blocks) => {
  const seen = new Set();
  const rows = [];

  for (const block of blocks) {
    for (const item of block.enums) {
      if (seen.has(item.name)) continue;
      seen.add(item.name);
      rows.push(
        `| ${code(item.name)} | ${item.members.map((member) => code(member)).join(", ")} |`,
      );
    }
  }

  if (rows.length === 0) return null;

  return ["| Enum | Members |", "| --- | --- |", ...rows].join("\n");
};

/** The prop types a README's markers ask for, resolved in marker order. */
export const resolveBlocks = (kit, folder, readme) =>
  [...readme.matchAll(PROPS_BLOCK)].map((match) => ({
    marker: match[1] ?? null,
    ...kit.resolveProps(folder, match[1] ?? null),
  }));

/** The README as it should be, with every generated block rewritten. */
export const renderBlocks = (readme, blocks) => {
  let index = 0;

  const withProps = readme.replace(PROPS_BLOCK, () => {
    const block = blocks[index];
    index += 1;

    return `<!-- props:start${block.marker ? ` ${block.marker}` : ""} -->\n\n${propsMarkdown(block)}\n\n<!-- props:end -->`;
  });

  const enums = enumsMarkdown(blocks) ?? "";

  return withProps.replace(
    ENUMS_BLOCK,
    () => `<!-- enums:start -->\n\n${enums}\n\n<!-- enums:end -->`,
  );
};

/**
 * Prettier, with the repository's own configuration. Every rendered README goes
 * through it before it is written or compared: `pnpm format` is a blocking
 * pre-push gate, so a table aligned by this script's rules would be reformatted
 * by Prettier and then reported as drift by the next `--check`.
 */
export const formatMarkdown = async (text, file) => {
  const config = await prettier.resolveConfig(
    file ?? path.join(ROOT, "README.md"),
  );
  return prettier.format(text, {
    ...config,
    filepath: file,
    parser: "markdown",
  });
};
