// The one TypeScript program the README tooling shares, and the prop model it
// produces. Both `readme-props.mjs` (which writes the tables) and
// `check-readme.mjs` (which checks they are current) read components through
// here, so a table can never be generated by one set of rules and validated by
// another -- that divergence is exactly what left the hand-written tables in
// this repository disagreeing with the types they claimed to describe.
//
// Three facts about this package shape the model below:
//
//   * A folder's `index` does not always export the raw component. Six of them
//     export a wrapper (`withTooltip(Button)`), whose props are wider than the
//     `<Name>Props` the folder declares. The wrapper's contribution is resolved
//     from the exported symbol and reported separately, because a reader who
//     only sees `ButtonProps` will not know `tooltipContent` is accepted.
//   * Props arrive from three places at once -- the component's own types, an
//     inherited kit type (`ModalDialogProps` takes ten from `AsideHeaderProps`)
//     and `@types/react` (`TextInputProps` takes about three hundred). They are
//     grouped by where the symbol is declared, not by how the type is written.
//   * A prop can be declared twice: the component narrows a React attribute
//     (`maxLength`, `placeholder`, `tabIndex` on TextInput). The checker hands
//     back one symbol with both declarations, and `declarations[0]` is React's,
//     so picking the first would file the component's own documented prop under
//     React and drop it from the table. The component's declaration wins.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// A namespace import, not a default one: under ESM the default export of
// `typescript` is missing `sys` and the config-file helpers.
import * as ts from "typescript";

import { toPosix, walk } from "./fs-ids.mjs";

export const ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../..",
);

const COMPONENTS_DIR = "components";

// `NoTruncation` because a truncated type is worse than a long one here;
// `UseAliasDefinedOutsideCurrentScope` keeps `ButtonSize` from expanding into
// its four members; `WriteArrowStyleSignature` prints handlers as a reader
// writes them.
const TYPE_FLAGS =
  ts.TypeFormatFlags.NoTruncation |
  ts.TypeFormatFlags.UseAliasDefinedOutsideCurrentScope |
  ts.TypeFormatFlags.WriteArrowStyleSignature;

/** `components/modal-dialog` and `modal-dialog` alike become `ModalDialog`. */
export const pascalCase = (folder) =>
  path.posix
    .basename(toPosix(folder))
    .replace(/(^|-)(\w)/g, (_, __, c) => c.toUpperCase());

/** The folder's `index.tsx` or `index.ts`, or null when it has neither. */
export const indexFileOf = (folder) => {
  for (const name of ["index.tsx", "index.ts"]) {
    const full = path.join(ROOT, folder, name);
    if (fs.existsSync(full)) return full;
  }

  return null;
};

// Directories a component keeps its own machinery in. They have index modules
// and are not components: `components/calendar/utils/get-calendar-days` is a
// date helper, not something anyone imports or documents.
const INTERNAL_DIRS = new Set([
  "sub-components",
  "utils",
  "hooks",
  "skeletons",
  "__tests__",
]);

/**
 * Every documentable folder under `components/`, as POSIX ids relative to the
 * repository root.
 *
 * Directly under `components/` an index module is enough -- that is what a
 * component is here. Deeper than that, a folder counts only once it has a
 * README of its own: `components/rows/row` and `components/aside/aside-header`
 * are real sub-components a consumer imports, while the eight index modules
 * under `components/calendar/utils` are not, and nothing in the file system
 * tells them apart.
 */
export function componentFolders() {
  const folders = [];

  for (const entry of walk(path.join(ROOT, COMPONENTS_DIR), {
    sort: true,
    enterDir: (dirent) => !INTERNAL_DIRS.has(dirent.name),
  })) {
    if (!entry.isDir || INTERNAL_DIRS.has(entry.name)) continue;

    const folder = `${COMPONENTS_DIR}/${entry.id}`;
    if (!indexFileOf(folder)) continue;

    const nested = entry.id.includes("/");

    if (!nested || fs.existsSync(path.join(ROOT, folder, "README.md"))) {
      folders.push(folder);
    }
  }

  return folders;
}

const readTsConfig = () => {
  const configPath = path.join(ROOT, "tsconfig.json");
  const { config, error } = ts.readConfigFile(configPath, ts.sys.readFile);

  if (error) {
    throw new Error(
      `tsconfig.json: ${ts.flattenDiagnosticMessageText(error.messageText, "\n")}`,
    );
  }

  return ts.parseJsonConfigFileContent(config, ts.sys, ROOT);
};

/**
 * A program over the repository plus the given files, with the package's own
 * specifier resolved to the source tree -- so a README example that imports
 * `@onlyoffice/apps-ui-kit/components/button` compiles here exactly as it will
 * for a consumer who installed the package.
 *
 * The repository's own file list is kept and the examples are added to it. An
 * earlier attempt compiled the extracted blocks alone and lost the ambient
 * environment they rely on (`*.react.svg` module declarations, `process`,
 * `Buffer`), which produced a wall of errors from `components/avatar`,
 * `components/context-menu`, `components/room-icon` and `components/tooltip`
 * that had nothing to do with any README.
 */
export function createExampleProgram(files) {
  const { options, fileNames } = readTsConfig();

  return ts.createProgram([...fileNames, ...files], {
    ...options,
    noEmit: true,
    // An example declares what it needs and uses all of it, but a reader's
    // eye, not this flag, is what should judge that.
    noUnusedLocals: false,
    noUnusedParameters: false,
    baseUrl: ROOT,
    paths: {
      "@onlyoffice/apps-ui-kit": ["./index.ts"],
      "@onlyoffice/apps-ui-kit/*": ["./*"],
    },
  });
}

/**
 * The name of the interface or type alias a property is declared in. It is the
 * nearest named ancestor, not the immediate parent: `AsideHeaderProps` is a
 * type alias over an object literal, so the property's parent is the literal
 * and the name is one level further up.
 */
const declaringTypeName = (declaration) => {
  let node = declaration.parent;

  while (node) {
    if (ts.isInterfaceDeclaration(node) || ts.isTypeAliasDeclaration(node)) {
      return node.name.getText();
    }

    node = node.parent;
  }

  return null;
};

/** One line, no internal newlines, safe to put in a table cell. */
const oneLine = (text) => text.replace(/\s*\r?\n\s*/g, " ").trim();

/**
 * Splits a type string on its top-level unions, ignoring the `|` inside
 * generics, object literals, tuples and parentheses.
 */
const topLevelUnion = (text) => {
  const parts = [];
  let depth = 0;
  let start = 0;

  for (let i = 0; i < text.length; i += 1) {
    const c = text[i];
    if (c === "<" || c === "(" || c === "{" || c === "[") depth += 1;
    // The `>` of an arrow closes nothing: counting it left every handler type
    // one level too shallow, and the `| undefined` of an optional handler was
    // then read as part of the return type and kept.
    else if (c === ">" && text[i - 1] === "=") continue;
    else if (c === ">" || c === ")" || c === "}" || c === "]") depth -= 1;
    else if (c === "|" && depth === 0) {
      parts.push(text.slice(start, i).trim());
      start = i + 1;
    }
  }

  parts.push(text.slice(start).trim());
  return parts.filter(Boolean);
};

/** True when one pair of parentheses encloses the whole string. */
const wrappedInParens = (text) => {
  if (!text.startsWith("(") || !text.endsWith(")")) return false;

  let depth = 0;

  for (let i = 0; i < text.length; i += 1) {
    if (text[i] === "(") depth += 1;
    else if (text[i] === ")") {
      depth -= 1;
      if (depth === 0) return i === text.length - 1;
    }
  }

  return false;
};

/**
 * Prints a prop's type for a table cell: without the `undefined` an optional
 * prop always carries -- the Required column already says it -- and with the
 * union members sorted.
 *
 * Sorting is not cosmetic. TypeScript orders union constituents by the order it
 * created the types in, so `inputMode` printed its eight members one way when
 * the program held one component and another way when it held all 99, and the
 * table a pre-push `--only` run had just written was reported stale by CI.
 */
const printableType = (text, optional) => {
  const parts = topLevelUnion(text)
    .filter((part) => !optional || part !== "undefined")
    .sort((a, b) => a.localeCompare(b));

  if (parts.length === 0) return text;

  // A lone handler is printed parenthesised only because it was a union
  // member; with `undefined` gone the parentheses are noise.
  return parts.length === 1 && wrappedInParens(parts[0])
    ? parts[0].slice(1, -1)
    : parts.join(" | ");
};

export function createReadmeProgram(folders = componentFolders()) {
  const roots = folders.map(indexFileOf).filter(Boolean);
  const program = ts.createProgram(roots, {
    ...readTsConfig().options,
    noEmit: true,
  });
  const checker = program.getTypeChecker();

  const relative = (fileName) => toPosix(path.relative(ROOT, fileName));

  /** The folder a declaration belongs to, or null when it is not in one. */
  const folderOfFile = (fileName) => {
    const rel = relative(fileName);
    if (!rel.startsWith(`${COMPONENTS_DIR}/`) || rel.startsWith("..")) {
      return null;
    }

    // Walk up to the nearest directory with an `index` module: a declaration in
    // `components/tooltip/sub-components/createTooltipWrapper.tsx` belongs to
    // `components/tooltip`.
    let dir = path.posix.dirname(rel);
    while (dir.startsWith(COMPONENTS_DIR) && dir !== COMPONENTS_DIR) {
      if (indexFileOf(dir)) return dir;
      dir = path.posix.dirname(dir);
    }

    return null;
  };

  const moduleSymbolOf = (folder) => {
    const file = indexFileOf(folder);
    const source = file && program.getSourceFile(file);
    if (!source) return null;

    return checker.getSymbolAtLocation(source) ?? null;
  };

  /** Named exports of a folder's `index`, and whether it has a default. */
  const folderExports = (folder) => {
    const moduleSymbol = moduleSymbolOf(folder);
    if (!moduleSymbol) return { names: [], hasDefault: false };

    const names = checker
      .getExportsOfModule(moduleSymbol)
      .map((symbol) => symbol.getName());

    return {
      names: names.filter((name) => name !== "default").sort(),
      hasDefault: names.includes("default"),
    };
  };

  /**
   * The folders `components/index.ts` re-exports -- the 68 a consumer can
   * import from the root barrel. Derived, never taken from a README.
   */
  const barrelFolders = () => {
    // Parsed from disk rather than taken from the program: nothing imports
    // `components/index.ts`, so it is not reachable from the component index
    // modules the program is rooted at, and asking the program for it returned
    // nothing -- which read as "no component is in the barrel".
    const file = path.join(ROOT, COMPONENTS_DIR, "index.ts");
    if (!fs.existsSync(file)) return new Set();

    const source = ts.createSourceFile(
      file,
      fs.readFileSync(file, "utf8"),
      ts.ScriptTarget.ESNext,
      true,
    );

    const found = new Set();

    for (const statement of source.statements) {
      if (
        (ts.isExportDeclaration(statement) ||
          ts.isImportDeclaration(statement)) &&
        statement.moduleSpecifier &&
        ts.isStringLiteral(statement.moduleSpecifier)
      ) {
        const specifier = statement.moduleSpecifier.text;
        if (specifier.startsWith("./")) {
          found.add(`${COMPONENTS_DIR}/${specifier.slice(2)}`);
        }
      }
    }

    return found;
  };

  /**
   * Defaults a component applies by destructuring its props. `@default` in the
   * JSDoc wins over this, because a default applied in a sub-component -- the
   * 255 of TextInput's `maxLength` -- is not visible here at all.
   */
  const destructuringDefaults = (folder) => {
    const defaults = new Map();
    const dir = path.join(ROOT, folder);

    // `title = LOADER_STYLE.title` is true but useless in a table: the reader
    // wants the value, not the name of the constant holding it. Follow one hop
    // to the property of a shared constant object and print what it says.
    const literalOf = (expression) => {
      if (!ts.isPropertyAccessExpression(expression)) return undefined;

      // `Object.freeze` returns `Readonly<T>`, whose properties are synthesized
      // by the mapped type and carry no `valueDeclaration` -- but they still
      // point back at the property assignment they were built from.
      const symbol = checker.getSymbolAtLocation(expression.name);
      const declaration = symbol?.valueDeclaration ?? symbol?.declarations?.[0];

      if (!declaration || !ts.isPropertyAssignment(declaration))
        return undefined;

      const value = declaration.initializer;

      if (
        ts.isStringLiteral(value) ||
        ts.isNumericLiteral(value) ||
        value.kind === ts.SyntaxKind.TrueKeyword ||
        value.kind === ts.SyntaxKind.FalseKeyword
      )
        return value.getText();

      // Two hops happen: the skeletons default to `LOADER_STYLE.backgroundColor`,
      // which is itself `globalColors.darkBlack`.
      return literalOf(value);
    };

    const files = fs
      .readdirSync(dir, { withFileTypes: true })
      .filter((e) => e.isFile() && /\.tsx?$/.test(e.name))
      .map((e) => path.join(dir, e.name));

    for (const file of files) {
      const source = program.getSourceFile(file);
      if (!source) continue;

      const record = (pattern) => {
        for (const element of pattern.elements) {
          if (!element.initializer || !ts.isIdentifier(element.name)) continue;

          const name = (element.propertyName ?? element.name).getText();
          if (!defaults.has(name)) {
            defaults.set(
              name,
              literalOf(element.initializer) ?? element.initializer.getText(),
            );
          }
        }
      };

      // Two shapes, and the second is the common one here: Button, ModalDialog
      // and most of the kit take `props` whole and destructure it in the body,
      // so reading only the parameter list found no defaults at all.
      const visit = (node, propsParameter) => {
        let parameterName = propsParameter;

        if (ts.isFunctionLike(node)) {
          const first = node.parameters[0];
          parameterName = undefined;

          if (first && ts.isObjectBindingPattern(first.name))
            record(first.name);
          else if (first && ts.isIdentifier(first.name)) {
            parameterName = first.name.getText();
          }
        }

        if (
          parameterName &&
          ts.isVariableDeclaration(node) &&
          ts.isObjectBindingPattern(node.name) &&
          node.initializer &&
          ts.isIdentifier(node.initializer) &&
          node.initializer.getText() === parameterName
        ) {
          record(node.name);
        }

        ts.forEachChild(node, (child) => visit(child, parameterName));
      };

      visit(source, undefined);
    }

    return defaults;
  };

  /**
   * The documentation of the declaration that won, not of every declaration
   * the symbol has. `symbol.getDocumentationComment` concatenates them, so a
   * prop the component narrows came out as React's sentence run together with
   * the kit's: "...while editing the element or its contents Input mode for
   * virtual keyboard".
   */
  const documentationOf = (symbol, declaration) => {
    const own = (declaration.jsDoc ?? [])
      .map((block) => ts.getTextOfJSDocComment(block.comment) ?? "")
      .filter(Boolean)
      .join(" ");

    return oneLine(
      own ||
        ts.displayPartsToString(symbol.getDocumentationComment(checker)) ||
        "",
    );
  };

  /**
   * Prop names the folder picks out of a foreign type by hand, as in
   * `Pick<React.InputHTMLAttributes<HTMLInputElement>, "name" | "onChange">`.
   *
   * They are declared in `@types/react`, so origin alone files them with the
   * three hundred attributes that collapse into one closing line -- and that
   * buried `onChange` and `name` on ToggleButton, the two props without which
   * the component does nothing. Naming a prop in a `Pick` is a deliberate act;
   * it belongs in the table.
   */
  const pickedNames = (folder) => {
    const names = new Set();
    const dir = path.join(ROOT, folder);

    const files = fs
      .readdirSync(dir, { withFileTypes: true })
      .filter((entry) => entry.isFile() && /\.tsx?$/.test(entry.name))
      .map((entry) => path.join(dir, entry.name));

    for (const file of files) {
      const source = program.getSourceFile(file);
      if (!source) continue;

      const visit = (node) => {
        if (
          ts.isTypeReferenceNode(node) &&
          node.typeName.getText() === "Pick" &&
          node.typeArguments?.length === 2
        ) {
          const selector = node.typeArguments[1];
          const members = ts.isUnionTypeNode(selector)
            ? selector.types
            : [selector];

          for (const member of members) {
            if (
              ts.isLiteralTypeNode(member) &&
              ts.isStringLiteral(member.literal)
            ) {
              names.add(member.literal.text);
            }
          }
        }

        ts.forEachChild(node, visit);
      };

      visit(source);
    }

    return names;
  };

  const describeProp = (symbol, folder, defaults, picked) => {
    const declarations = symbol.declarations ?? [];

    // The component's own declaration wins over the React attribute it
    // narrows; a kit declaration wins over a `node_modules` one.
    const scored = declarations.map((declaration) => {
      const owner = folderOfFile(declaration.getSourceFile().fileName);
      return { declaration, owner, rank: owner === folder ? 0 : owner ? 1 : 2 };
    });
    scored.sort((a, b) => a.rank - b.rank);

    const home = scored[0];
    if (!home) return null;

    const { declaration, owner } = home;
    const type = checker.getTypeOfSymbolAtLocation(symbol, declaration);
    const optional = Boolean(symbol.flags & ts.SymbolFlags.Optional);
    const printed = checker.typeToString(type, declaration, TYPE_FLAGS);

    const tags = new Map(
      symbol
        .getJsDocTags(checker)
        .map((tag) => [tag.name, ts.displayPartsToString(tag.text ?? [])]),
    );

    const name = symbol.getName();
    const taggedDefault = tags.get("default")?.trim();
    const destructured = owner === folder ? defaults.get(name) : undefined;

    return {
      name,
      optional,
      type: printableType(printed, optional),
      description: documentationOf(symbol, declaration),
      default: taggedDefault || destructured || null,
      // Both say a default and they disagree: the JSDoc is stale, or the
      // destructuring is dead. Reported, never silently resolved.
      defaultConflict:
        taggedDefault && destructured && taggedDefault !== destructured
          ? { tagged: taggedDefault, destructured }
          : null,
      deprecated: tags.has("deprecated"),
      deprecatedReason: tags.get("deprecated")?.trim() || null,
      portal: tags.has("portal"),
      origin:
        owner === folder
          ? "own"
          : owner
            ? "kit"
            : picked.has(name)
              ? "picked"
              : "external",
      ownerFolder: owner,
      declaredFile: relative(declaration.getSourceFile().fileName),
      // The type that declares the prop, which is what a group heading and the
      // closing React line name: `AsideHeaderProps`, `InputHTMLAttributes`.
      declaredIn: declaringTypeName(declaration),
    };
  };

  const enumsOf = (type, seen) => {
    const found = [];

    const consider = (candidate) => {
      const symbol = candidate.aliasSymbol ?? candidate.symbol;
      const declaration = symbol?.declarations?.[0];
      if (!declaration) return;

      // An enum member's type points at the member; its parent is the enum.
      const enumDeclaration = ts.isEnumDeclaration(declaration)
        ? declaration
        : ts.isEnumMember(declaration)
          ? declaration.parent
          : null;

      if (!enumDeclaration) return;

      const name = enumDeclaration.name.getText();
      if (seen.has(name)) return;
      seen.add(name);

      found.push({
        name,
        members: enumDeclaration.members.map((member) =>
          member.name.getText().replace(/^["']|["']$/g, ""),
        ),
      });
    };

    consider(type);
    if (type.isUnion()) for (const part of type.types) consider(part);

    return found;
  };

  /**
   * A type declared in the folder's own files, whether or not the index
   * re-exports it. Several folders declare `<Name>Props` and export only the
   * component -- Aside, SearchInput, ModalDialog -- and resolving those through
   * the call signature printed the whole intersection where the alias was
   * wanted.
   */
  const declaredInFolder = (folder, typeName) => {
    const dir = path.join(ROOT, folder);

    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (!entry.isFile() || !/\.tsx?$/.test(entry.name)) continue;

      const source = program.getSourceFile(path.join(dir, entry.name));
      if (!source) continue;

      for (const statement of source.statements) {
        if (
          (ts.isTypeAliasDeclaration(statement) ||
            ts.isInterfaceDeclaration(statement)) &&
          statement.name.getText() === typeName
        ) {
          const symbol = checker.getSymbolAtLocation(statement.name);
          const type = symbol && checker.getDeclaredTypeOfSymbol(symbol);

          if (type) {
            return { type, file: relative(source.fileName) };
          }
        }
      }
    }

    return null;
  };

  /** The declared type of an exported type name, with the file declaring it. */
  const exportedType = (folder, typeName) => {
    const moduleSymbol = moduleSymbolOf(folder);
    if (!moduleSymbol) return declaredInFolder(folder, typeName);

    const symbol = checker
      .getExportsOfModule(moduleSymbol)
      .find((exported) => exported.getName() === typeName);
    if (!symbol) return declaredInFolder(folder, typeName);

    const target =
      symbol.flags & ts.SymbolFlags.Alias
        ? checker.getAliasedSymbol(symbol)
        : symbol;

    const type = checker.getDeclaredTypeOfSymbol(target);
    if (!type || type.flags === ts.TypeFlags.Any) return null;

    const declaration = target.declarations?.[0];
    return {
      type,
      file: declaration ? relative(declaration.getSourceFile().fileName) : null,
    };
  };

  /** The props type of the component the folder's `index` exports. */
  const exportedComponentProps = (folder) => {
    const moduleSymbol = moduleSymbolOf(folder);
    const source = program.getSourceFile(indexFileOf(folder));
    if (!moduleSymbol || !source) return null;

    const exports = checker.getExportsOfModule(moduleSymbol);
    const wanted = pascalCase(folder);
    const symbol =
      exports.find((e) => e.getName() === wanted) ??
      exports.find((e) => e.getName() === "default");
    if (!symbol) return null;

    const type = checker.getTypeOfSymbolAtLocation(symbol, source);
    const signature = type.getCallSignatures()[0];
    const parameter = signature?.getParameters()?.[0];
    if (!parameter) return null;

    return checker.getTypeOfSymbolAtLocation(parameter, source);
  };

  /**
   * Resolves the props of one component and groups them.
   *
   * The chain is: the type named in the `props:start` marker, then the folder's
   * exported `<Name>Props`, then the first parameter of the exported
   * component's call signature. The named type is preferred because it prints
   * the types a reader recognises -- resolving Button through its wrapper
   * renders `onClick` as an intersection with the wrapper's own handler.
   */
  const resolveProps = (folder, typeName = null) => {
    const defaults = destructuringDefaults(folder);
    const picked = pickedNames(folder);
    const wanted = typeName ?? `${pascalCase(folder)}Props`;

    const declared = exportedType(folder, wanted);
    const componentProps = exportedComponentProps(folder);
    const base = declared?.type ?? componentProps;

    if (!base) {
      const error = new Error(
        `${folder}: no props type. Export \`${wanted}\` from the folder's index, ` +
          "or name the type in the marker: `<!-- props:start TypeName -->`.",
      );
      error.code = "E_PROPS_TYPE_NOT_FOUND";
      throw error;
    }

    const describe = (type) =>
      checker
        .getPropertiesOfType(type)
        .map((symbol) => describeProp(symbol, folder, defaults, picked))
        .filter(Boolean);

    const baseProps = describe(base);
    const known = new Set(baseProps.map((prop) => prop.name));

    // "What does the exported component accept beyond this type?" is only a
    // question when the component accepts this type at all. A marker naming a
    // satellite -- `TBreadCrumb`, `TSelectorItem`, `HeaderProps` -- resolves a
    // type the component never takes, and the diff against it is the component's
    // entire prop list, printed again under every such table.
    const componentNames = componentProps
      ? new Set(
          checker.getPropertiesOfType(componentProps).map((s) => s.getName()),
        )
      : null;

    const describesTheComponent =
      componentNames !== null &&
      baseProps.length > 0 &&
      baseProps.every((prop) => componentNames.has(prop.name));

    // What the exported wrapper accepts on top of the declared type. Empty for
    // the 92 folders whose index exports the component itself.
    const wrapperProps =
      declared && componentProps && describesTheComponent
        ? describe(componentProps).filter((prop) => !known.has(prop.name))
        : [];

    const seenEnums = new Set();
    const enums = [];

    // Only the kit's own enums: a reader needs `ButtonSize`'s members spelled
    // out, not React's string unions.
    for (const type of [base, componentProps].filter(Boolean)) {
      for (const symbol of checker.getPropertiesOfType(type)) {
        const declaration = symbol.declarations?.[0];
        if (!declaration) continue;

        const owner = folderOfFile(declaration.getSourceFile().fileName);
        if (!owner) continue;

        enums.push(
          ...enumsOf(
            checker.getTypeOfSymbolAtLocation(symbol, declaration),
            seenEnums,
          ),
        );
      }
    }

    return {
      folder,
      typeName: declared ? wanted : checker.typeToString(base),
      typeFile:
        declared?.file ??
        baseProps.find((prop) => prop.origin === "own")?.declaredFile ??
        null,
      baseProps,
      wrapperProps,
      enums,
    };
  };

  return {
    program,
    checker,
    relative,
    folderOfFile,
    folderExports,
    barrelFolders,
    resolveProps,
  };
}
