/*
 * Copyright (C) Ascensio System SIA, 2009-2026
 *
 * This program is a free software product. You can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License (AGPL)
 * version 3 as published by the Free Software Foundation, together with the
 * additional terms provided in the LICENSE file.
 *
 * This program is distributed WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For
 * details, see the GNU AGPL at: https://www.gnu.org/licenses/agpl-3.0.html
 *
 * You can contact Ascensio System SIA by email at info@onlyoffice.com
 * or by postal mail at 20A-6 Ernesta Birznieka-Upisha Street, Riga,
 * LV-1050, Latvia, European Union.
 *
 * The interactive user interfaces in modified versions of the Program
 * are required to display Appropriate Legal Notices in accordance with
 * Section 5 of the GNU AGPL version 3.
 *
 * No trademark rights are granted under this License.
 *
 * All non-code elements of the Product, including illustrations,
 * icon sets, and technical writing content, are licensed under the
 * Creative Commons Attribution-ShareAlike 4.0 International License:
 * https://creativecommons.org/licenses/by-sa/4.0/legalcode
 *
 * This license applies only to such non-code elements and does not
 * modify or replace the licensing terms applicable to the Program's
 * source code, which remains licensed under the GNU Affero General
 * Public License v3.
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

// Declaration emit mirrors the source tree, which means it also inherits the
// source's non-TypeScript imports. Two kinds need handling before the types are
// consumable outside this repository:
//
//   1. Side-effect stylesheet imports (`import "./X.scss";`). A .d.ts is never
//      executed, so these carry no information, but a consumer's TypeScript
//      still tries to resolve them and fails without an ambient declaration.
//      They are removed.
//   2. Real SVG re-exports (`export { default as Icon } from "./x.svg"`). These
//      do carry information, so instead an ambient declaration is shipped and
//      referenced from the files that need it.

import fs from "node:fs";
import path from "node:path";

const TYPES = path.resolve(
  path.dirname(new URL(import.meta.url).pathname),
  "../dist/types",
);

const GLOBALS = "globals.d.ts";

const AMBIENT = `// Ambient declarations for the non-TypeScript modules this package re-exports.
// Generated by scripts/normalize-types.mjs -- do not edit by hand.

declare module "*.svg" {
  import type * as React from "react";
  const ReactComponent: React.FC<React.SVGProps<SVGSVGElement>>;
  export default ReactComponent;
}

declare module "*.svg?url" {
  const url: string;
  export default url;
}
`;

const SIDE_EFFECT_STYLE = /^import\s+"[^"]+\.(?:s?css)";?\s*$/gm;
const REFERENCES_SVG = /(?:from|module)\s+"[^"]+\.svg"/;

const walk = (dir, out = []) => {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else if (entry.name.endsWith(".d.ts")) out.push(full);
  }
  return out;
};

if (!fs.existsSync(TYPES)) {
  console.error("dist/types not found -- run the declaration build first.");
  process.exit(1);
}

fs.writeFileSync(path.join(TYPES, GLOBALS), AMBIENT);

const files = walk(TYPES);
let stripped = 0;
let referenced = 0;

for (const file of files) {
  if (path.basename(file) === GLOBALS) continue;

  const original = fs.readFileSync(file, "utf8");
  let next = original.replace(SIDE_EFFECT_STYLE, "");

  if (next !== original) stripped += 1;

  if (REFERENCES_SVG.test(next)) {
    const rel = path
      .relative(path.dirname(file), path.join(TYPES, GLOBALS))
      .split(path.sep)
      .join("/");
    const ref = `/// <reference path="${rel.startsWith(".") ? rel : `./${rel}`}" />\n`;

    if (!next.startsWith("/// <reference")) {
      next = ref + next;
      referenced += 1;
    }
  }

  if (next !== original) fs.writeFileSync(file, next);
}

console.log(
  `Normalized ${files.length} declaration files: ` +
    `stripped stylesheet imports from ${stripped}, ` +
    `referenced ambient SVG types from ${referenced}.`,
);
