/*
 * Copyright (C) Ascensio System SIA, 2009-2026
 *
 * This program is a free software product. You can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License (AGPL)
 * version 3 as published by the Free Software Foundation, together with the
 * additional terms provided in the LICENSE file.
 *
 * This program is distributed WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For
 * details, see the GNU AGPL at: https://www.gnu.org/licenses/agpl-3.0.html
 *
 * You can contact Ascensio System SIA by email at info@onlyoffice.com
 * or by postal mail at 20A-6 Ernesta Birznieka-Upisha Street, Riga,
 * LV-1050, Latvia, European Union.
 *
 * The interactive user interfaces in modified versions of the Program
 * are required to display Appropriate Legal Notices in accordance with
 * Section 5 of the GNU AGPL version 3.
 *
 * No trademark rights are granted under this License.
 *
 * All non-code elements of the Product, including illustrations,
 * icon sets, and technical writing content, are licensed under the
 * Creative Commons Attribution-ShareAlike 4.0 International License:
 * https://creativecommons.org/licenses/by-sa/4.0/legalcode
 *
 * This license applies only to such non-code elements and does not
 * modify or replace the licensing terms applicable to the Program's
 * source code, which remains licensed under the GNU Affero General
 * Public License v3.
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

// Declaration emit mirrors the source tree, which means it also inherits the
// source's non-TypeScript imports. Two kinds need handling before the types are
// consumable outside this repository:
//
//   1. Side-effect stylesheet imports (`import "./X.scss";`). A .d.ts is never
//      executed, so these carry no information, but a consumer's TypeScript
//      still tries to resolve them and fails without an ambient declaration.
//      They are removed.
//   2. Real SVG re-exports (`export { default as Icon } from "./x.svg"`). These
//      do carry information, so instead an ambient declaration is shipped and
//      referenced from the files that need it.

import fs from "node:fs";
import path from "node:path";

const TYPES = path.resolve(
  path.dirname(new URL(import.meta.url).pathname),
  "../dist/types",
);

const GLOBALS = "globals.d.ts";

const AMBIENT = `// Ambient declarations for the non-TypeScript modules this package re-exports.
// Generated by scripts/normalize-types.mjs -- do not edit by hand.

declare module "*.svg" {
  import type * as React from "react";
  const ReactComponent: React.FC<React.SVGProps<SVGSVGElement>>;
  export default ReactComponent;
}

declare module "*.svg?url" {
  const url: string;
  export default url;
}
`;

const SIDE_EFFECT_STYLE = /^import\s+"[^"]+\.(?:s?css)";?\s*$/gm;

// `export { default as Icon } from "../../assets/x.react.svg"` cannot stand in
// a published declaration: `assets/` is not in `files`, and the built code
// re-exports the svgr-compiled `x.react.svg.js` instead, which has no
// declaration of its own. attw reports the mismatch as the types
// misrepresenting the JavaScript. Rewriting each re-export to a concrete React
// component type removes the unresolvable specifier and says what the module
// actually provides.
const SVG_REEXPORT =
  /export\s*\{\s*default as (\w+)\s*\}\s*from\s*"[^"]+\.svg";?/g;

const SVG_COMPONENT_TYPE =
  'React.FunctionComponent<React.SVGProps<SVGSVGElement> & { title?: string }>';

const rewriteSvgReexports = (text) => {
  if (!SVG_REEXPORT.test(text)) return null;

  SVG_REEXPORT.lastIndex = 0;

  const body = text.replace(
    SVG_REEXPORT,
    (_match, name) => `export declare const ${name}: ${SVG_COMPONENT_TYPE};`,
  );

  return `import type * as React from "react";\n${body}`;
};

const walk = (dir, out = []) => {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else if (entry.name.endsWith(".d.ts")) out.push(full);
  }
  return out;
};

if (!fs.existsSync(TYPES)) {
  console.error("dist/types not found -- run the declaration build first.");
  process.exit(1);
}

fs.writeFileSync(path.join(TYPES, GLOBALS), AMBIENT);

const files = walk(TYPES);
let stripped = 0;
let referenced = 0;

for (const file of files) {
  if (path.basename(file) === GLOBALS) continue;

  const original = fs.readFileSync(file, "utf8");
  let next = original.replace(SIDE_EFFECT_STYLE, "");

  if (next !== original) stripped += 1;

  const svgRewritten = rewriteSvgReexports(next);

  if (svgRewritten !== null) {
    next = svgRewritten;
    referenced += 1;
  }

  if (next !== original) fs.writeFileSync(file, next);
}

// A second, ESM-flavoured copy of every declaration, so the package can offer
// per-condition types: `.d.ts` for `require`, `.d.mts` for `import`. Without it
// the types resolve as CommonJS while the JavaScript is ESM, which publint
// reports as ambiguous and attw as "masquerading as CJS".
//
// A plain copy is not enough. Declarations use extensionless relative
// specifiers, and `export * from "./components"` is a *directory* import: legal
// under CommonJS resolution, which falls back to index, and invalid under ESM,
// which needs an explicit file. Each specifier is therefore resolved against
// the emitted tree and rewritten to point at a real .d.mts file.
const RELATIVE_SPECIFIER = /(from\s*|import\s*\(\s*)"(\.[^"]*)"/g;

const toEsmSpecifier = (fromFile, specifier) => {
  const base = path.resolve(path.dirname(fromFile), specifier);
  const asFile = `${base}.d.mts`;
  const asDir = path.join(base, "index.d.mts");

  const target = fs.existsSync(asFile)
    ? asFile
    : fs.existsSync(asDir)
      ? asDir
      : null;

  if (!target) return null;

  const rel = path
    .relative(path.dirname(fromFile), target)
    .split(path.sep)
    .join("/");

  return rel.startsWith(".") ? rel : `./${rel}`;
};

let mjsWritten = 0;
let rewritten = 0;

// Two passes: every .d.mts must exist before specifiers can be resolved.
for (const file of files) {
  fs.copyFileSync(file, `${file.slice(0, -".d.ts".length)}.d.mts`);
  mjsWritten += 1;
}

for (const file of files) {
  const mts = `${file.slice(0, -".d.ts".length)}.d.mts`;
  const original = fs.readFileSync(mts, "utf8");
  const next = original.replace(
    RELATIVE_SPECIFIER,
    (match, prefix, specifier) => {
      const resolved = toEsmSpecifier(mts, specifier);
      return resolved ? `${prefix}"${resolved}"` : match;
    },
  );

  if (next !== original) {
    fs.writeFileSync(mts, next);
    rewritten += 1;
  }
}

console.log(
  `Normalized ${files.length} declaration files: ` +
    `stripped stylesheet imports from ${stripped}, ` +
    `inlined SVG component types in ${referenced}; ` +
    `wrote ${mjsWritten} .d.mts copies, rewrote specifiers in ${rewritten}.`,
);
