// Writes the prop tables of the component READMEs, between the `props:start` /
// `props:end` and `enums:start` / `enums:end` markers.
//
//   pnpm readme:props --write                      every component
//   pnpm readme:props --write --only button        one, folder name or path
//   pnpm readme:props:check                        fails when a table is stale
//
// The tables are generated because the hand-written ones drifted: Button's
// omitted `accent`, Section's listed six props against roughly 129 in the type,
// Selector's 58 against 360. A description therefore has exactly one home --
// the JSDoc on the prop -- which is also what Storybook's autodocs reads, so
// the README and the story can no longer disagree.
//
// Output is run through Prettier before it is written or compared, because
// `pnpm format` is a blocking pre-push gate: a table this script aligned by its
// own rules would be reformatted by Prettier and then reported as drift by the
// next `--check`.

import fs from "node:fs";
import path from "node:path";

import prettier from "prettier";

import {
  ROOT,
  componentFolders,
  createReadmeProgram,
} from "./lib/readme-program.mjs";

const PROPS_BLOCK =
  /<!-- props:start(?: ([A-Za-z0-9_]+))? -->[\s\S]*?<!-- props:end -->/g;
const ENUMS_BLOCK = /<!-- enums:start -->[\s\S]*?<!-- enums:end -->/g;

// Two props React declares that a consumer passes deliberately and that change
// what the component does. Every other inherited React prop collapses into the
// closing line: TextInput alone has about three hundred of them.
const PROMOTED_REACT_PROPS = new Set(["children", "ref"]);

const MAX_TYPE_LENGTH = 120;

const usage = () => {
  console.error(
    "usage: node scripts/readme-props.mjs (--write | --check) [--only <folder>...]",
  );
  process.exit(2);
};

const parseArgs = (argv) => {
  const options = { write: false, check: false, only: [] };

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--write") options.write = true;
    else if (arg === "--check") options.check = true;
    else if (arg === "--only") {
      while (argv[i + 1] && !argv[i + 1].startsWith("--")) {
        options.only.push(argv[(i += 1)]);
      }
    } else usage();
  }

  if (options.write === options.check) usage();
  return options;
};

/** `button`, `components/button` and `components\button` all name the folder. */
const normaliseFolder = (input) => {
  const posix = input.replaceAll("\\", "/").replace(/\/$/, "");
  return posix.startsWith("components/") ? posix : `components/${posix}`;
};

const cell = (text) => text.replaceAll("|", "\\|");

const code = (text) => `\`${cell(text)}\``;

const typeCell = (type) =>
  code(
    type.length > MAX_TYPE_LENGTH
      ? `${type.slice(0, MAX_TYPE_LENGTH - 1)}…`
      : type,
  );

const describeCell = (prop) => {
  const description = prop.deprecated
    ? `**Deprecated.** ${prop.deprecatedReason || prop.description}`.trim()
    : prop.description;

  return cell(description);
};

const table = (props) =>
  [
    "| Prop | Type | Required | Default | Description |",
    "| --- | --- | --- | --- | --- |",
    ...props.map((prop) =>
      [
        "",
        code(prop.name),
        typeCell(prop.type),
        prop.optional ? "no" : "**yes**",
        prop.default ? code(prop.default) : "–",
        describeCell(prop),
        "",
      ].join(" | "),
    ),
  ].join("\n");

/** Required props first, then alphabetical: the reader's first question. */
const ordered = (props) =>
  [...props].sort(
    (a, b) =>
      Number(a.optional) - Number(b.optional) || a.name.localeCompare(b.name),
  );

const englishList = (items) =>
  items.length <= 1
    ? (items[0] ?? "")
    : `${items.slice(0, -1).join(", ")} and ${items.at(-1)}`;

const groupBy = (items, key) => {
  const groups = new Map();

  for (const item of items) {
    const value = key(item);
    if (!groups.has(value)) groups.set(value, []);
    groups.get(value).push(item);
  }

  return groups;
};

const propsMarkdown = (resolved) => {
  const lines = [];
  const source = resolved.typeFile
    ? path.posix.basename(resolved.typeFile)
    : resolved.typeName;

  lines.push(
    `_Generated by \`pnpm readme:props\` from \`${resolved.typeName}\` in \`${source}\`. Do not edit; edit the JSDoc._`,
    "",
  );

  const all = resolved.baseProps;
  const promoted = (prop) =>
    prop.origin !== "external" || PROMOTED_REACT_PROPS.has(prop.name);

  const own = all.filter((prop) => prop.origin === "own" && !prop.portal);
  const portal = all.filter((prop) => prop.origin === "own" && prop.portal);
  const inherited = all.filter((prop) => prop.origin === "kit" && !prop.portal);
  const external = all.filter((prop) => prop.origin === "external");

  lines.push(table(ordered([...own, ...external.filter(promoted)])), "");

  for (const [folder, props] of groupBy(inherited, (p) => p.ownerFolder)) {
    const from = props[0].declaredIn ?? path.posix.basename(folder);
    lines.push(
      `#### Inherited from \`${from}\``,
      "",
      `Declared by [\`${folder}\`](../../${folder}/README.md) and accepted here too.`,
      "",
      table(ordered(props)),
      "",
    );
  }

  if (resolved.wrapperProps.length > 0) {
    lines.push(
      "#### Added by the wrapper the folder exports",
      "",
      "The `index` module exports a wrapped component, so these are accepted on top of the props above.",
      "",
      table(ordered(resolved.wrapperProps.filter(promoted))),
      "",
    );
  }

  if (portal.length > 0) {
    lines.push(
      "#### Portal-only props",
      "",
      "These need DocSpace portal context and do nothing in a standalone app.",
      "",
      table(ordered(portal)),
      "",
    );
  }

  const collapsed = external.filter((prop) => !promoted(prop));

  if (collapsed.length > 0) {
    // Sorted, so the line does not depend on the order the checker happens to
    // hand back properties in.
    const interfaces = [
      ...new Set(collapsed.map((prop) => prop.declaredIn).filter(Boolean)),
    ]
      .sort()
      .map((name) => `\`React.${name}\``);

    lines.push(
      `Plus ${collapsed.length} more props inherited from ${englishList(interfaces)}, forwarded to the element.`,
      "",
    );
  }

  return lines.join("\n").trimEnd();
};

const enumsMarkdown = (resolved) => {
  if (resolved.enums.length === 0) return null;

  return [
    "| Enum | Members |",
    "| --- | --- |",
    ...resolved.enums.map(
      (item) =>
        `| ${code(item.name)} | ${item.members.map((member) => code(member)).join(", ")} |`,
    ),
  ].join("\n");
};

const render = (readme, resolved) => {
  let index = 0;

  const withProps = readme.replace(PROPS_BLOCK, (_, typeName) => {
    const block = resolved[index];
    index += 1;
    void typeName;

    return `<!-- props:start${block.marker ? ` ${block.marker}` : ""} -->\n\n${propsMarkdown(block)}\n\n<!-- props:end -->`;
  });

  const enums = resolved.map(enumsMarkdown).filter(Boolean).join("\n\n");

  return withProps.replace(
    ENUMS_BLOCK,
    () => `<!-- enums:start -->\n\n${enums}\n\n<!-- enums:end -->`,
  );
};

const main = async () => {
  const options = parseArgs(process.argv.slice(2));
  const folders =
    options.only.length > 0
      ? options.only.map(normaliseFolder)
      : componentFolders();

  const withReadme = folders.filter((folder) =>
    fs.existsSync(path.join(ROOT, folder, "README.md")),
  );

  // Every component, whatever `--only` asked for: the program is what the
  // tables are derived from, and narrowing it changes them. With text-input
  // alone the type printed `Ref<HTMLInputElement>` and counted 285 inherited
  // React props; with all 99 loaded, `React.Ref<HTMLInputElement>` and 299. A
  // pre-push `--only` run would then write a table CI reports as stale. The
  // whole program costs about three seconds.
  const kit = createReadmeProgram();
  const prettierConfig = await prettier.resolveConfig(
    path.join(ROOT, "README.md"),
  );

  const stale = [];
  const failed = [];
  let written = 0;

  for (const folder of withReadme) {
    const file = path.join(ROOT, folder, "README.md");
    const readme = fs.readFileSync(file, "utf8");

    const markers = [...readme.matchAll(PROPS_BLOCK)];
    if (markers.length === 0) continue;

    let blocks;
    try {
      blocks = markers.map((match) => ({
        marker: match[1] ?? null,
        ...kit.resolveProps(folder, match[1] ?? null),
      }));
    } catch (error) {
      failed.push(`${folder}: ${error.message}`);
      continue;
    }

    const rendered = render(readme, blocks);
    const formatted = await prettier.format(rendered, {
      ...prettierConfig,
      filepath: file,
    });

    if (formatted === readme) continue;

    if (options.write) {
      fs.writeFileSync(file, formatted, "utf8");
      written += 1;
      console.log(`wrote ${folder}/README.md`);
    } else {
      stale.push(folder);
    }
  }

  for (const message of failed) console.error(`error  ${message}`);

  if (options.check && stale.length > 0) {
    console.error(
      `\n${stale.length} README prop table(s) are out of date:\n` +
        stale.map((folder) => `  ${folder}/README.md`).join("\n") +
        "\n\nRun `pnpm readme:props --write` and commit the result. Do not edit " +
        "between the markers by hand -- change the JSDoc on the prop instead.",
    );
    process.exit(1);
  }

  if (failed.length > 0) process.exit(2);

  console.log(
    options.write
      ? `${written} README(s) updated, ${withReadme.length - written} already current.`
      : `${withReadme.length} README(s) checked, every prop table is current.`,
  );
};

await main();
